### ISSUE TITLE
Readiness Probe

### ISSUE THREAD

**Issue by Rollmops** [Rollmops/pctl#4]
Add support for adding a readiness probe to the process configuration

- no (default): start the process and hope it to be started
- script: specify a script or a command that checks whether a process is ready -> returns status 0
- http: define an HTTP request that should return status 200

Example config:

```
processes:
- name: p1
  cmd: [start, command]
  readinessProbe:
    script: 
      cmd: [test, -f, file.pid]
      args: [${cmd}, ${name}]
```
